apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wszyujgh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-wszyujgh:6b174a9d7989304f2b0ecede852e11f6697bb1db@sha256:af030f24941c982eb90865ff77cc0822be2a672f3b5411f333eb31a856645b22
          name: container-image
